### ISSUE TITLE
Precision column in diat_ips() output

### ISSUE THREAD

**Issue by xbenitogranell** [limnolab/DiaThor#2]
Congrats for this useful package! How do I interpret the 'precision' column from `diatom_ips`? Proportion of species present in my sample and internal package database? Thanks!

**Comment by jcochero** [comment]
Thank you for trying it out Xavi! We are still tuning it, but it's getting there!
Yes, the precision column indicates the % of species in your input data that in fact get used to calculate the index in each sample. 
So this includes the number of species matched to the internal DB but also have >0% abundance in the sample.
We will be releasing an update for the package soon, and proper documentation to explain the details!

**Comment by xbenitogranell** [comment]
Great, thanks so much! Looking forward to using the updated package.
